version: "3.7"

services:
  server:
    build:
      context: .
      args:
        # default 1 core
        BUILD_CORES: ${BUILD_CORES:-1}
    restart: always
    volumes:
      - .:/srv
    ports:
      - "7171:7171"
      - "7172:7172"
